### ISSUE TITLE
[BUG] Spelling: Protocal => Protocol on the VPC Flow Logs 1.0 Filters

### ISSUE THREAD

**Issue by smacrakis** [opensearch-project/opensearch-catalog#143]
**What is the bug?**
"Protocol" is misspelled

**How can one reproduce the bug?**
1. Go to [VPC Flow Logs Filters](https://playground.opensearch.org/app/visualize#/edit/28cdab5d-e9d8-41c5-86f5-4d293e236bc7?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(filters:!(),linked:!f,query:(language:kuery,query:''),uiState:(),vis:(aggs:!(),params:(controls:!((fieldName:aws.vpc.account-id,id:'1689743740550',indexPattern:'7e8bc395-9ad3-4e47-a499-9ab93d48b78c',label:'Account%20ID',options:(dynamicOptions:!t,multiselect:!t,order:desc,size:5,type:terms),parent:'',type:list),(fieldName:cloud.resource_id,id:'1689745980222',indexPattern:'7e8bc395-9ad3-4e47-a499-9ab93d48b78c',label:'VPC%20ID',options:(dynamicOptions:!t,multiselect:!t,order:desc,size:5,type:terms),parent:'',type:list),(fieldName:aws.vpc.action,id:'1689743798842',indexPattern:'7e8bc395-9ad3-4e47-a499-9ab93d48b78c',label:Action,options:(dynamicOptions:!t,multiselect:!t,order:desc,size:5,type:terms),parent:'',type:list),(fieldName:aws.vpc.log-status,id:'1689745214045',indexPattern:'7e8bc395-9ad3-4e47-a499-9ab93d48b78c',label:Status,options:(dynamicOptions:!t,multiselect:!t,order:desc,size:5,type:terms),parent:'',type:list),(fieldName:aws.vpc.protocol,id:'1689745255475',indexPattern:'7e8bc395-9ad3-4e47-a499-9ab93d48b78c',label:Protocal,options:(dynamicOptions:!t,multiselect:!t,order:desc,size:5,type:terms),parent:'',type:list),(fieldName:communication.source.address.keyword,id:'1689745303238',indexPattern:'7e8bc395-9ad3-4e47-a499-9ab93d48b78c',label:Source,options:(dynamicOptions:!t,multiselect:!t,order:desc,size:5,type:terms),parent:'',type:list),(fieldName:communication.destination.address.keyword,id:'1689745349390',indexPattern:'7e8bc395-9ad3-4e47-a499-9ab93d48b78c',label:Destination,options:(dynamicOptions:!t,multiselect:!t,order:desc,size:5,type:terms),parent:'',type:list)),pinFilters:!f,updateFiltersOnChange:!f,useTimeFilter:!f),title:'%5BAWS%20VPC%20Flow%20Logs%201.0%5D%20Filters',type:input_control_vis))
)
2. Notice the misspelling "Protocal" in several places:
* the list of filters; 
* The "Protocal" section on the right
* The default value for the "Control Label"
3. 
**What is the expected behavior?**
Change "a" to "o".

**What is your host/environment?**
 - OS: MacOS
 - Version OpenSearch 2.12.0
 - Plugins

**Do you have any screenshots?**
![Screenshot 2024-03-27 at 12 26 45](https://github.com/opensearch-project/opensearch-catalog/assets/134456002/47f3118b-84fa-4ccb-9ae9-9db89a996074)

**Do you have any additional context?**

**Comment by Swiddis** [comment]
Oh, that's embarrassing... Thanks for the issue! Made a PR over at the deployed content to fix this: https://github.com/opensearch-project/dashboards-observability/pull/1638

**Comment by Swiddis** [comment]
@YANG-DB can you mark this as triaged & close the issue when the PR is merged? Not a maintainer here so I can't track it.

There might also need to be a corresponding PR on this repo for content parity.
