### ISSUE TITLE
[BUG] Otel Services Demo is broken

### ISSUE THREAD

**Issue by spapadop** [opensearch-project/opensearch-catalog#170]
**What is the bug?**
The "Otel Services Demo" that comes by default on cluster installation does not work. There is an error produced on creating index templates and then the dashboards are broken.

**How can one reproduce the bug?**
1. Go to "Integrations"
2. Click on "Available"
3. Click on "Otel Services Demo"
4. Click on "Try It"
5. See the "Bad request" error produced

**What is the expected behavior?**
The "Try It" button should not produce any errors and the demo dashboards/visualisations should work.

**What is your host/environment?**
 - OS: AlmaLinux
 - Version 9.4
 - OpenSearch version 2.15.0
 - Plugins: all the default + repository-s3

**Do you have any screenshots?**
![Screenshot 2024-07-03 at 16 36 45](https://github.com/opensearch-project/opensearch-catalog/assets/5896507/308c5261-a2fc-4f4a-8424-e5cf48882736)

**Do you have any additional context?**
Checking the logs, it's likely that the wrong path is used in order to create the index templates. I see `path=_component_template%2Fss4o_services-1.0.1-template&method=POST`. Maybe here it should had been `path=_index_template`?

**Comment by YANG-DB** [comment]
@spapadop thanks for your comments - we will review and upload a fix to the [otel demo catalog release repo](https://github.com/opensearch-project/opensearch-catalog/releases/tag/otel_services_dashboard-1.0.0)
