### ISSUE TITLE
[Integration]Python Integration

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-catalog#172]
**What is the integration resource ?**

As part of the `getting-started` campaign, we are adding additional un-structured integrations so that it will be simpler and easily available to ingest telemetry logs data directly into opensearch using one of the available ingestion ways.
 - Data prepper 
 - Fluet-Bit
 - Python Client API

**What is the integration source protocol ?**

Mainly applicative logs using Python

**What is the integration target protocol ?**
Since this is an unstructured log we have no schema defined for the integration

**Which agents would you use to ship this data ?**
 - Data prepper 
 - Fluet-Bit
 - Python Client API

**Would you be using an ingestion pipeline ?**

 - Data prepper 

**Which Dashboards would you be using ?**

A single tutorial markdown based dashboard will be added to explain how to generate a generic applicative logs dashboards so the customer could easily start ingesting and inspecting application health.

Default Analytics target for this log will be the Discover Plugin.
----

**Do you have any additional context?**
 - https://github.com/opensearch-project/dashboards-observability/issues/1929 
 - https://opensearch.org/docs/latest/clients/python-high-level/

**Comment by Swiddis** [comment]
Can you help me understand what a python integration would do? There's a lot of different types of applications written in Python, a "Python" integration doesn't make much sense on its own. Similar issue applies to the other language issues like #173 and #171 (though the log4j one is slightly better)

**Comment by YANG-DB** [comment]
The purpose of these general purpose integrations are the following:
 - Setup a getting started tutorial for using python-client to ingest applicative telemetry into opensearch
 - Introduce a dashboard containing these instructions + dashboard tutorial for visualize the applicative info using the Dashboard
