### ISSUE TITLE
[FEATURE] Rename index schema compositions

### ISSUE THREAD

**Issue by Swiddis** [opensearch-project/opensearch-catalog#29]
### Is your feature request related to a problem?
In the `composed_of` field for schemas, we use names of types followed by `_template`, such as `"composed_of": ["http_template", "communication_template"]`. In practice, we actually rename these, dynamically linking to the component templates being referenced. The component template names are potentially variable due to name collision concerns. This inconsistency would make the replacement code trickier.

### What solution would you like?
When pulling the schemas into the dashboards-observability codebase, we already replace the templates with a templateless name. [See current PR for example](https://github.com/opensearch-project/dashboards-observability/blob/19da5bc0b1f0b6920e8938e75689669f471803bf/server/adaptors/integrations/__data__/repository/nginx/schemas/logs-1.0.0.mapping.json#L222-L223). This solution works fine, but would be broken by efforts to dynamically load the catalog at build time, so we need to make the issue upstream.

### What alternatives have you considered?
We can also write code to do this conversion itself, removing a `_template` suffix from every schema. This adds a bit of overhead to the user to make sure to always include it, and would require documentation to verify that it's mandatory. The new proposed system would make it clear that the schema name has to match the component name, which is more reliable long-term.

### Do you have any additional context?
Relevant to [dashboards-observability/#569](https://github.com/opensearch-project/dashboards-observability/pull/569).

**Comment by YANG-DB** [comment]
this is taken care of as part of the recent schema updates
