### ISSUE TITLE
[FEATURE] Add URL and User_Agent Mappings

### ISSUE THREAD

**Issue by danieldong51** [opensearch-project/opensearch-catalog#40]
### Is your feature request related to a problem?
The AWS_ELB dashboard depends on fields contained in `url` schemas that the catalog does not yet have. Other integrations will have more fields that are not in existing schemas.

### What solution would you like?
Adding missing schema files required for future integrations. 

### What alternatives have you considered?
None

### Do you have any additional context?
- https://www.elastic.co/guide/en/ecs/current/ecs-user_agent.html
- https://www.elastic.co/guide/en/ecs/current/ecs-url.html

**Comment by YANG-DB** [comment]
use the http mapping: https://github.com/opensearch-project/opensearch-catalog/blob/b91f5ba6a869a4e2d5dbdd60da94c88c373beb7f/docs/schema/observability/logs/http.md?plain=1#L10
