### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-catalog#9]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by ananzh** [comment]
@rishabh6788 Could you help us to update the permissions and add a screenshot here? I think now build team should have admin access. Thanks.

**Comment by rishabh6788** [comment]
Access provided. 
![Screen Shot 2023-04-24 at 1 19 41 PM](https://user-images.githubusercontent.com/19776689/234107336-ae499967-f0c6-4bf2-9cc7-0a906142dd44.png)

**Comment by dblock** [comment]
Verified, thanks.
